done
bratizgut/network pull request #2
Opened 2020-10-08 13:13 UTC by bratizgut

2020-10-08 13:14 UTC, bratizgut commented
@Aloomenon

2020-10-11 13:15 UTC, Aloomenon requested changes
Все ли ресурсы освобождаете?

2020-10-11 13:36 UTC, bratizgut commented
> Все ли ресурсы освобождаете?

Потоки не закрываю, т.к. при закрытии сокетов, они автоматически закрываются

2020-10-13 18:53 UTC, bratizgut commented
@Aloomenon

2020-10-18 09:37 UTC, Aloomenon commented
Расскажите:
1) почему вы используете Digest Streams
2) почему остальные потоки также не закрываете.

2020-10-18 18:56 UTC, bratizgut commented
Digest Streams использую для того, чтобы считать хэш файла во время передачи для последующей проверки целостности передачи файла.
Остальные потоки не закрываю потому, что они закрываются при закрытии сокетов.

2020-10-18 18:56 UTC, bratizgut commented
@Aloomenon

2020-10-21 15:09 UTC, bratizgut commented
@Aloomenon

2020-10-25 08:59 UTC, Aloomenon commented
> Остальные потоки не закрываю потому, что они закрываются при закрытии сокетов.

Пруфы?

2020-10-25 09:56 UTC, bratizgut commented
@Aloomenon Closing this socket will also close the socket's InputStream and OutputStream. 
https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html

2020-11-06 17:46 UTC, bratizgut commented
@Aloomenon

2020-11-07 20:36 UTC, Aloomenon commented
Окей, принял. Имя и фамилию скажите.

2020-11-08 03:22 UTC, bratizgut commented
Кирилл Зонов

2020-11-08 03:22 UTC, bratizgut commented
@Aloomenon

2020-11-11 05:50 UTC, merged