Lab3
bratizgut/network pull request #3
Opened 2020-11-05 17:26 UTC by bratizgut

@Aloomenon

2020-11-07 05:34 UTC, bratizgut commented
@Aloomenon

2020-11-22 16:08 UTC, bratizgut commented
@Aloomenon

2020-11-24 07:14 UTC, Aloomenon requested changes

2020-11-24 07:14 UTC, Aloomenon commented on lab2/src/main/java/client/Client.java
> +    public Client(String IPaddress, int port) throws UnknownHostException, IOException {
КОгда тут вылетит Exception и к чему это приведет?

2020-11-24 10:45 UTC, bratizgut commented on lab2/src/main/java/client/Client.java
> +    public Client(String IPaddress, int port) throws UnknownHostException, IOException {
@Aloomenon Это не та лаба, я 2 уже сдал. Просто branch сделал не от той ветки))))

2020-11-24 19:14 UTC, Aloomenon commented on lab2/src/main/java/client/Client.java
> +    public Client(String IPaddress, int port) throws UnknownHostException, IOException {
Ну вот, не интересно таки.

2020-11-24 19:14 UTC, Aloomenon commented
Принял. Фамилию и имя скажите

2020-11-29 11:27 UTC, merged